Repository graph-quilt/graphql-xtext, pull requests merged in 2022-10, with the labels that each got.

#26 feature: adding autorc
  .autorc
  .github/workflows/master.yml
Labels: minor

#31 Trying auto
  README.md
Labels: major

#37 add fetch-depth
  .github/workflows/master.yml
Labels: minor

#38 Update README.md
  README.md
Labels: release

#39 Fix auto integration
  .github/workflows/master.yml
  .github/workflows/release.yml
  CHANGELOG.md
  pom.xml
Labels: release
